
services:

  web:
    build:
      target: dev
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: web_container
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/laravel
    depends_on:
      - app
  app:
    build:
      target: dev
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: app_container
    user: ${UID}:${GID}
    volumes:
      - ./app:/var/www/laravel
    ports:
      - "5173:5173"   
    depends_on:
      - db



  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: queue_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/entrypoint.sh:/entrypoint.sh  
    env_file:
      - .env  
    entrypoint: ["/bin/sh", "/entrypoint.sh"]  
    restart: always



volumes:
  mysql_data:
  redis_data:
 